loinc_data = [
    {'code': '29463-7', 'description': 'Body Weight', 'unit': 'kg'},
    {'code': '8302-2', 'description': 'Height', 'unit': 'cm'},
    {'code': '8462-4', 'description': 'Diastolic Blood Pressure', 'unit': 'mmHg'},
    {'code': '8480-6', 'description': 'Systolic Blood Pressure', 'unit': 'mmHg'},
    {'code': '8867-4', 'description': 'Heart Rate', 'unit': 'bpm'},
    {'code': '9279-1', 'description': 'Respiratory Rate', 'unit': 'breaths/min'},
    {'code': '8310-5', 'description': 'Body Temperature', 'unit': '°C'},
    {'code': '39156-5', 'description': 'Body Mass Index (BMI)', 'unit': 'kg/m2'},
    {'code': '85354-9', 'description': 'Mean Blood Pressure', 'unit': 'mmHg'},
    {'code': '72166-2', 'description': 'BMI ratio', 'unit': 'kg/m2'},
    {'code': '4548-4', 'description': 'Hemoglobin A1c/Hemoglobin.total in Blood', 'unit': '%'},
    {'code': '1751-7', 'description': 'Glucose [Mass/volume] in Blood', 'unit': 'mg/dL'},
    {'code': '6299-2', 'description': 'Cholesterol in LDL [Mass/volume]', 'unit': 'mg/dL'},
    {'code': '2093-3', 'description': 'Cholesterol [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '2571-8', 'description': 'Triglyceride [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '2951-2', 'description': 'Sodium [Moles/volume] in Serum', 'unit': 'mmol/L'},
    {'code': '2823-3', 'description': 'Potassium [Moles/volume] in Serum', 'unit': 'mmol/L'},
    {'code': '2075-0', 'description': 'Carbon dioxide [Partial pressure]', 'unit': 'mmHg'},
    {'code': '1988-5', 'description': 'Creatinine [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '2160-0', 'description': 'Creatinine [Mass/volume] in Blood', 'unit': 'mg/dL'},
    {'code': '2345-7', 'description': 'Glucose [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '3094-0', 'description': 'Urea nitrogen [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '2885-2', 'description': 'Protein [Mass/volume] in Serum', 'unit': 'g/dL'},
    {'code': '5792-7', 'description': 'HDL cholesterol [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '12957-2', 'description': 'Estimated GFR', 'unit': 'mL/min/1.73m2'},
    {'code': '6690-2', 'description': 'Leukocytes [#/volume] in Blood', 'unit': '10^3/uL'},
    {'code': '718-7', 'description': 'Hemoglobin [Mass/volume] in Blood', 'unit': 'g/dL'},
    {'code': '789-8', 'description': 'Erythrocytes [#/volume] in Blood', 'unit': '10^6/uL'},
    {'code': '777-3', 'description': 'Hematocrit [Volume Fraction] of Blood', 'unit': '%'},
    {'code': '785-6', 'description': 'MCV [Entitic volume] of Red Blood Cells', 'unit': 'fL'},
    {'code': '786-4', 'description': 'MCH [Entitic mass] of Red Blood Cells', 'unit': 'pg'},
    {'code': '787-2', 'description': 'MCHC [Mass/volume] of Red Blood Cells', 'unit': 'g/dL'},
    {'code': '788-0', 'description': 'RDW [Ratio] of Red Blood Cells', 'unit': '%'},
    {'code': '26515-7', 'description': 'Platelets [#/volume] in Blood', 'unit': '10^3/uL'},
    {'code': '721-1', 'description': 'Hemoglobin A1c', 'unit': '%'},
    {'code': '1920-8', 'description': 'Calcium [Mass/volume] in Serum', 'unit': 'mg/dL'},
    {'code': '1925-7', 'description': 'Calcium Ionized', 'unit': 'mmol/L'},
    {'code': '22748-8', 'description': 'Vitamin D [Mass/volume] in Serum', 'unit': 'ng/mL'},
    {'code': '3024-7', 'description': 'Albumin [Mass/volume] in Serum', 'unit': 'g/dL'},
    {'code': '3040-3', 'description': 'Alkaline Phosphatase', 'unit': 'U/L'},
    {'code': '6768-6', 'description': 'Alanine aminotransferase (ALT)', 'unit': 'U/L'},
    {'code': '6769-4', 'description': 'Aspartate aminotransferase (AST)', 'unit': 'U/L'},
    {'code': '58410-2', 'description': 'C-reactive protein [Mass/volume] in Serum', 'unit': 'mg/L'},
    {'code': '5811-5', 'description': 'Ferritin [Mass/volume] in Serum', 'unit': 'ng/mL'},
    {'code': '48642-3', 'description': 'TSH [Units/volume] in Serum', 'unit': 'uIU/mL'},
    {'code': '2588-2', 'description': 'Thyroxine (T4) free', 'unit': 'ng/dL'},
    {'code': '14957-5', 'description': 'Troponin I [Mass/volume] in Serum', 'unit': 'ng/mL'},
]